[colors.primary]
background = '#171308'
foreground = '#ece1cf'

[colors.selection]
text = '#ece1cf'
background = '#5b3774'

[colors.cursor]
text = '#171308'
cursor = '#e2b6fd'

[colors.normal]
black   = '#171308'
red     = '#ff7289'
green   = '#7efd9d'
yellow  = '#ffdc72'
blue    = '#d19ff0'
magenta = '#5e3875'
cyan    = '#e2b6fd'
white   = '#f9efff'

[colors.bright]
black   = '#9f98a4'
red     = '#ff9faf'
green   = '#a5ffbb'
yellow  = '#ffe8a5'
blue    = '#e7c2ff'
magenta = '#ebccff'
cyan    = '#f2deff'
white   = '#fcf8ff'
